### PR TITLE
added REALTIME option for viewing snapshots thru web

### PR DESCRIPTION
**Pull request by euquiq**
Now you can watch any camera for new valid snapshots in realtime. It uses SignalR for keeping each web client updated on any new snapshot.

Captura de Pantalla 2021-09-10 a la(s) 00 37 24

It is faster than any external notification (like -say- Telegram) so it is an interesting addition i.e. "to see who's at your door" or similar.

I also renamed some webpages so they make more sense.

### CODE REVIEW

**Comment by lucasCFO** [comment]
Great feature!

I think it will be more practical to have one button to access the RT mode. And then when you are on the new window the ability to choose between your different cameras (list, button, arrow ? I don't know 😃).

Also, it would be great that when you enter the RT window, it shows the last image taken and not a blank page.

What do you think?

**Comment by euquiq** [comment]
@lucasCFO Thanks. Well, what you comment, in part "it is somewhat there": On the main webpage, when all cameras are listed, there is a "View in Realtime" link at each camera name side ...

Same thing when you are viewing the graphs for an hour (or a minute) for a specific camera, the link is there too.

About viewing the last snapshot on start, problem is that the RT webpage is "passively" waiting for the server to communicate a new Snapshot, and when it arrives, the page verifies it is for the camera you chose to view and then it displays it. There is no mechanism in place at this time for the RT page to "ask" for anything. But it could be done, yes. 

About a link to other cameras, it should be trivial to add. Maybe you could create an "issue" with these ideas so we can have them present, whenever anyone is able to add some hours to this nice project ?

**Comment by lucasCFO** [comment]
Is there a way to specify a branch when creating an issue?
Should I wait the merge to avoid any confusion?

**Comment by djdd87** [comment]
Just mention which branch it's for in the ticket.

**Pull request merged**
